---
- name: Advanced loops examples
  hosts: localhost
  become: yes
  vars:
    list1:
      - 3
      - 2
      - 1
    list2:
      - 4
      - 5
      - 6
    list3:
      - 7
      - 8
      - 9

  tasks:
    - name: display variables
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ list1 }}"
        - "{{ list2 }}"
        - "{{ list3 }}"
   
    - name: display variables from flaten
      debug:
        msg:  "{{ item }}"
      loop: "{{ list_of_lists | flatten(levels=1) }}"
      vars:
        list_of_lists:
          - "{{ list1 }}"
          - "{{ list2 }}"
          - "{{ list3 }}"
